import {chipsFor,outcome,payout} from './logic.js';
const enc=new TextEncoder();
const uid=()=>crypto.randomUUID();
const rand=()=>{const a=new Uint32Array(1);crypto.getRandomValues(a);return a[0]};
const secret=()=>{const a=new Uint8Array(24);crypto.getRandomValues(a);return Array.from(a,b=>b.toString(16).padStart(2,'0')).join('')};
const hash=async s=>Array.from(new Uint8Array(await crypto.subtle.digest('SHA-256',enc.encode(s))),b=>b.toString(16).padStart(2,'0')).join('');
const json=(x,status=200,headers={})=>new Response(JSON.stringify(x),{status,headers:{'content-type':'application/json; charset=utf-8','cache-control':'no-store',...headers}});
const fail=(msg,status=400)=>json({error:msg},status);
const cookie=(token)=>`session=${token}; HttpOnly; Secure; SameSite=Lax; Path=/; Max-Age=2592000`;
const parseCookie=s=>s?.match(/(?:^|;\s*)session=([^;]+)/)?.[1];
async function player(req,env){const token=parseCookie(req.headers.get('cookie'));if(!token)return null;return env.DB.prepare('SELECT p.* FROM sessions s JOIN players p ON p.id=s.player_id WHERE s.token_hash=? AND s.expires_at>?').bind(await hash(token),Date.now()).first()}
async function admin(req,env){const pw=req.headers.get('x-admin-key');if(!pw||!env.ADMIN_KEY||pw.length!==env.ADMIN_KEY.length)return false;const a=enc.encode(pw),b=enc.encode(env.ADMIN_KEY);let diff=0;for(let i=0;i<a.length;i++)diff|=a[i]^b[i];return diff===0}
async function settings(db){const rows=await db.prepare('SELECT key,value FROM settings').all();return Object.fromEntries(rows.results.map(x=>[x.key,x.value]))}
async function body(req){const x=await req.json();if(!x||typeof x!=='object'||Array.isArray(x))throw Error('Неверные данные');return x}
function checkOpen(s){if(s.contest_open!=='true')throw Error('Конкурс пока закрыт');const now=Date.now();if(s.start_at&&now<Date.parse(s.start_at))throw Error('Конкурс ещё не начался');if(s.end_at&&now>Date.parse(s.end_at))throw Error('Конкурс завершён')}
async function audit(db,actor,action,subject,details={}){await db.prepare('INSERT INTO audit(id,actor,action,subject,details) VALUES(?,?,?,?,?)').bind(uid(),actor,action,subject,JSON.stringify(details)).run()}
async function route(req,env){const url=new URL(req.url),path=url.pathname,method=req.method,db=env.DB;
 if(!db)return fail('База данных не подключена',503);
 if(path==='/api/public'&&method==='GET'){const s=await settings(db);return json({contact:s.contact,cashiers:JSON.parse(s.cashiers),prizes:JSON.parse(s.prizes),start_at:s.start_at,end_at:s.end_at,contest_open:s.contest_open==='true',final_open:s.final_open==='true',over_10000:s.over_10000})}
 if(path==='/api/register'&&method==='POST'){
 const x=await body(req),id=String(x.id||'').trim();if(!/^\d{5,20}$/.test(id))return fail('ID: от 5 до 20 цифр');const s=await settings(db);checkOpen(s);
 const existing=await db.prepare('SELECT id FROM players WHERE id=?').bind(id).first();if(existing)return fail('Этот ID уже зарегистрирован. Войдите с ключом доступа.',409);
 const access=secret(),token=secret();await db.batch([db.prepare('INSERT INTO players(id,access_hash) VALUES(?,?)').bind(id,await hash(access)),db.prepare('INSERT INTO sessions(token_hash,player_id,expires_at) VALUES(?,?,?)').bind(await hash(token),id,Date.now()+2592000000)]);
 return json({id,access_key:access,message:'Сохраните ключ доступа: он потребуется для входа с другого устройства.'},201,{'set-cookie':cookie(token)})}
 if(path==='/api/login'&&method==='POST'){const x=await body(req),id=String(x.id||''),key=String(x.access_key||'');const p=await db.prepare('SELECT id FROM players WHERE id=? AND access_hash=?').bind(id,await hash(key)).first();if(!p)return fail('Неверный ID или ключ доступа',401);const token=secret();await db.prepare('INSERT INTO sessions(token_hash,player_id,expires_at) VALUES(?,?,?)').bind(await hash(token),id,Date.now()+2592000000).run();return json({id},200,{'set-cookie':cookie(token)})}
 if(path==='/api/logout'&&method==='POST'){const token=parseCookie(req.headers.get('cookie'));if(token)await db.prepare('DELETE FROM sessions WHERE token_hash=?').bind(await hash(token)).run();return json({ok:true},200,{'set-cookie':'session=; HttpOnly; Secure; SameSite=Lax; Path=/; Max-Age=0'})}
 if(path==='/api/leaderboard'&&method==='GET'){const r=await db.prepare('SELECT id,chips FROM players ORDER BY chips DESC,created_at ASC,id ASC LIMIT 50').all();return json({leaders:r.results})}
 if(path.startsWith('/api/admin/')){
 if(!await admin(req,env))return fail('Нет доступа',401);
 if(path==='/api/admin/overview'&&method==='GET'){const [r,p,a,s]=await Promise.all([db.prepare('SELECT id,player_id,status,amount,chips_awarded,created_at FROM requests ORDER BY created_at DESC LIMIT 150').all(),db.prepare('SELECT id,chips FROM players ORDER BY chips DESC LIMIT 150').all(),db.prepare('SELECT * FROM audit ORDER BY created_at DESC LIMIT 100').all(),settings(db)]);return json({requests:r.results,players:p.results,audit:a.results,settings:s})}
 if(path==='/api/admin/settings'&&method==='POST'){const x=await body(req);const allowed=['contact','cashiers','prizes','start_at','end_at','contest_open','final_open','over_10000'];if(!allowed.includes(x.key))return fail('Неизвестная настройка');let value=String(x.value??'');if(['cashiers','prizes'].includes(x.key)){const v=JSON.parse(value);if(!Array.isArray(v))return fail('Ожидается JSON-массив');value=JSON.stringify(v)}if(['contest_open','final_open'].includes(x.key)&&!['true','false'].includes(value))return fail('Допустимо true или false');if(x.key==='contact'&&!/^https:\/\/t\.me\/[a-zA-Z0-9_]{5,32}$/.test(value))return fail('Укажите ссылку t.me');await db.prepare('UPDATE settings SET value=? WHERE key=?').bind(value,x.key).run();await audit(db,'admin','setting',x.key,{value});return json({ok:true})}
 if(path==='/api/admin/decide'&&method==='POST'){
 const x=await body(req);if(!['approved','rejected'].includes(x.decision))return fail('Неверное решение');const r=await db.prepare('SELECT * FROM requests WHERE id=?').bind(String(x.request_id||'')).first();if(!r)return fail('Заявка не найдена',404);if(r.status!=='pending')return fail('Заявка уже обработана',409);
 if(x.decision==='rejected'){const u=await db.prepare("UPDATE requests SET status='rejected',decided_at=CURRENT_TIMESTAMP WHERE id=? AND status='pending'").bind(r.id).run();if(!u.meta.changes)return fail('Заявка уже обработана',409);await audit(db,'admin','reject',r.id);return json({ok:true})}
 const amount=Number(x.amount),manual=Number(x.manual_chips);let chips=chipsFor(amount);if(chips===null){if(!Number.isSafeInteger(manual)||manual<1||manual>100000000)return fail('Для суммы выше 10 000 ₽ укажите согласованное число фишек');chips=manual}
 const sid=uid();const statements=[db.prepare("UPDATE requests SET status='approved',amount=?,chips_awarded=?,decided_at=CURRENT_TIMESTAMP WHERE id=? AND status='pending'").bind(amount,chips,r.id),db.prepare('UPDATE players SET chips=chips+?,version=version+1 WHERE id=?').bind(chips,r.player_id),db.prepare('INSERT INTO series(id,request_id,player_id,stake,current) VALUES(?,?,?,?,?)').bind(sid,r.id,r.player_id,chips,chips),db.prepare('INSERT INTO audit(id,actor,action,subject,details) VALUES(?,?,?,?,?)').bind(uid(),'admin','approve',r.id,JSON.stringify({amount,chips}))];
 // All four statements run in a D1 atomic batch; a failed statement rolls back the batch.
 await db.batch(statements);return json({ok:true,chips})}
 return fail('Неизвестный адрес',404)}
 const p=await player(req,env);if(!p)return fail('Войдите в аккаунт',401);
 if(path==='/api/me'&&method==='GET'){const [requests,series]=await Promise.all([db.prepare('SELECT id,status,amount,chips_awarded,created_at FROM requests WHERE player_id=? ORDER BY created_at DESC LIMIT 50').bind(p.id).all(),db.prepare('SELECT id,stake,current,spins,status FROM series WHERE player_id=? ORDER BY created_at DESC LIMIT 50').bind(p.id).all()]);return json({id:p.id,chips:p.chips,requests:requests.results,series:series.results})}
 if(path==='/api/request'&&method==='POST'){const s=await settings(db);checkOpen(s);const code=secret().slice(0,12).toUpperCase();const id=uid();await db.prepare('INSERT INTO requests(id,player_id,code_hash) VALUES(?,?,?)').bind(id,p.id,await hash(code)).run();return json({request_id:id,code,message:'Сохраните код и передайте его кассиру вместе с ID.'},201)}
 if(path==='/api/activate'&&method==='POST'){const x=await body(req),code=String(x.code||'').trim().toUpperCase();const r=await db.prepare('SELECT id,status FROM requests WHERE player_id=? AND code_hash=?').bind(p.id,await hash(code)).first();if(!r)return fail('Код не найден',404);if(r.status!=='issued')return fail('Этот код уже активирован или обработан',409);const u=await db.prepare("UPDATE requests SET status='pending',activated_at=CURRENT_TIMESTAMP WHERE id=? AND status='issued'").bind(r.id).run();if(!u.meta.changes)return fail('Код уже активирован',409);return json({ok:true,request_id:r.id,status:'pending'})}
 if(path==='/api/spin'&&method==='POST'){
 const x=await body(req),choice=String(x.choice||''),sid=String(x.series_id||'');if(!['red','black','even','odd','zero'].includes(choice))return fail('Неверная ставка');const s=await settings(db);checkOpen(s);
 const series=await db.prepare('SELECT * FROM series WHERE id=? AND player_id=?').bind(sid,p.id).first();if(!series||series.status==='closed'||series.spins>=2)return fail('Серия недоступна',409);if(series.spins===1&&series.status!=='won')return fail('Серия завершена',409);
 const n=rand()%37,result=outcome(n),win=choice==='even'?n!==0&&n%2===0:choice==='odd'?n%2===1:choice===result;const won=win?(choice==='zero'?series.current*3:series.current*2):0;const delta=won-series.current;
 // Guarded update prevents a second concurrent spin from consuming the same series state.
 const update=await db.prepare('UPDATE series SET current=?,spins=spins+1,status=? WHERE id=? AND player_id=? AND spins=? AND status=? AND current=?').bind(won,won>0&&series.spins===0?'won':'closed',sid,p.id,series.spins,series.status,series.current).run();if(!update.meta.changes)return fail('Серия уже изменилась; обновите страницу',409);
 await db.batch([db.prepare('UPDATE players SET chips=chips+?,version=version+1 WHERE id=?').bind(delta,p.id),db.prepare('INSERT INTO spins(id,series_id,player_id,choice,outcome,payout) VALUES(?,?,?,?,?,?)').bind(uid(),sid,p.id,choice,String(n),won)]);
 return json({number:n,result,won,delta,spins:series.spins+1,status:won>0&&series.spins===0?'won':'closed'})}
 if(path==='/api/collect'&&method==='POST'){const x=await body(req);const u=await db.prepare("UPDATE series SET status='closed' WHERE id=? AND player_id=? AND status='won' AND spins=1").bind(String(x.series_id||''),p.id).run();if(!u.meta.changes)return fail('Нечего забирать',409);return json({ok:true})}
 return fail('Неизвестный адрес',404)
}
export default {async fetch(req,env){const url=new URL(req.url);if(!url.pathname.startsWith('/api/'))return env.ASSETS.fetch(req);try{return await route(req,env)}catch(e){if(e instanceof SyntaxError)return fail('Неверный JSON');if(['Конкурс пока закрыт','Конкурс ещё не начался','Конкурс завершён','Неверная сумма'].includes(e.message))return fail(e.message,409);console.error(e);return fail('Ошибка сервера',500)}}};
